#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")
# trigger:
# - main

resources:
  repositories:
    - repository: self
      trigger: 
      - master

stages:
- stage: Build
  displayName: Build .Net Core Solution
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.sln'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.sln'
    
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: 'tests/UnitTests/*.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-o $(Build.ArtifactStagingDirectory)'
    
    - task: PublishPipelineArtifact@1
      displayName: Publish Artifacts ADO - Website
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'Website'
        publishLocation: 'pipeline'

    - task: PublishPipelineArtifact@1
      displayName: Publish Artifacts ADO - Bicep
      inputs:
        targetPath: '$(Build.SourcesDirectory)/MyWebApiProject/infra/webapp.bicep'
        artifact: 'Bicep'
        publishLocation: 'pipeline'

- stage: Deploy
  displayName: Deploy to an Azure Web App
  jobs:
    - deployment: Deploy
      environment: approvals
      pool:
        vmImage: "windows-latest"
      strategy:
        runOnce:
          deploy:
            steps: 
            - task: DownloadBuildArtifacts@1
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'Website'
                downloadPath: '$(Build.ArtifactStagingDirectory)'
            
            - task: AzureRmWebAppDeployment@5
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'azure subs'
                appType: 'webApp'
                WebAppName: 'eshoponWebYAML53829428'
                packageForLinux: '$(Build.ArtifactStagingDirectory)/**/MyWebApiProject.zip'
                ConfigurationSettings: '-UseOnlyInMemoryDatabase true -ASPNETCORE_ENVIRONMENT Development'

    